##House Pricing


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv("/content/Housing.csv")
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [ ]:
# @title area

from matplotlib import pyplot as plt
df['area'].plot(kind='hist', bins=20, title='area')
plt.gca().spines[['top', 'right',]].set_visible(False)

In [5]:
encoder = LabelEncoder()

In [7]:
df["mainroad_encoded"] = encoder.fit_transform(df["mainroad"])

In [18]:
df["guestroom_encoded"] = encoder.fit_transform(df["guestroom"])
df["basement_encoded"] = encoder.fit_transform(df["basement"])
df["hotwaterheating_encoded"] = encoder.fit_transform(df["hotwaterheating"])
df["guestroom_encoded"] = encoder.fit_transform(df["guestroom"])
df["airconditioning_encoded"] = encoder.fit_transform(df["airconditioning"])
df["prefarea_encoded"] = encoder.fit_transform(df["prefarea"])
df["furnishingstatus_encoded"] = encoder.fit_transform(df["furnishingstatus"])

In [27]:
df = df.drop(columns=['airconditioning', "mainroad", "basement", "hotwaterheating", "guestroom", "airconditioning", "prefarea", "furnishingstatus"])

In [66]:
df

price  area  bedrooms  bathrooms  stories  parking  mainroad_encoded  \
0    13300000  7420         4          2        3        2                 1   
1    12250000  8960         4          4        4        3                 1   
2    12250000  9960         3          2        2        2                 1   
3    12215000  7500         4          2        2        3                 1   
4    11410000  7420         4          1        2        2                 1   
..        ...   ...       ...        ...      ...      ...               ...   
540   1820000  3000         2          1        1        2                 1   
541   1767150  2400         3          1        1        0                 0   
542   1750000  3620         2          1        1        0                 1   
543   1750000  2910         3          1        1        0                 0   
544   1750000  3850         3          1        2        0                 1   

     guestroom_encoded  basement_encoded  hotwaterheating_encoded  \
0                    0                 0                        0   
1                    0                 0                        0   
2                    0                 1                        0   
3                    0                 1                        0   
4                    1                 1                        0   
..                 ...               ...                      ...   
540                  0                 1                        0   
541                  0                 0                        0   
542                  0                 0                        0   
543                  0                 0                        0   
544                  0                 0                        0   

     airconditioning_encoded  prefarea_encoded  furnishingstatus_encoded  
0                          1                 1                         0  
1                          1                 0                         0  
2                          0                 1                         1  
3                          1                 1                         0  
4                          1                 0                         0  
..                       ...               ...                       ...  
540                        0                 0                         2  
541                        0                 0                         1  
542                        0                 0                         2  
543                        0                 0                         0  
544                        0                 0                         2  

[545 rows x 13 columns]

In [29]:
df["furnishingstatus_encoded"].unique()

array([0, 1, 2])

In [28]:
df.isna().sum()

price                       0
area                        0
bedrooms                    0
bathrooms                   0
stories                     0
parking                     0
mainroad_encoded            0
guestroom_encoded           0
basement_encoded            0
hotwaterheating_encoded     0
airconditioning_encoded     0
prefarea_encoded            0
furnishingstatus_encoded    0
dtype: int64

In [52]:
X, y =  df.drop(columns=["price"]), df["price"]

In [53]:
y = np.array(y).reshape(-1, 1)

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [55]:
linear = LinearRegression()

In [56]:
linear.fit(X_train, y_train)

LinearRegression()

In [57]:
y_pred = linear.predict(X_test)

In [64]:
y_pred[1]

array([3945490.16150523])

In [65]:
y_test[1]

array([4235000])

In [62]:
ems = mean_squared_error(y_test, y_pred)

In [63]:
ems

1176536697938.209

In [82]:
from sklearn.ensemble import RandomForestRegressor

In [83]:
rfr = RandomForestRegressor(n_estimators=100)

In [84]:
rfr.fit(X_train, y_train)

<ipython-input-84-e1b1f0422edb>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfr.fit(X_train, y_train)


RandomForestRegressor()

In [85]:
y_pred_r = rfr.predict(X_test)

In [86]:
y_test[4]

array([3430000])

In [87]:
y_pred_r[4]

3745910.0

In [88]:
mser = mean_squared_error(y_test, y_pred)

In [89]:
mser

1505479001704.5237